<a href="https://colab.research.google.com/github/ShakilAhmedSumon/numpy_exersises/blob/main/numpy_exersise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np_array = np.array([[0,1,2], [3,4,5], [6,7,8]])

In [3]:
np_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Numpy Slicing 

In [4]:
middle_slice = np_array[1::3]

In [5]:
middle_slice

array([[3, 4, 5]])

In [22]:
first_slice = np_array[:1:3]
first_slice

array([[0, 1, 2]])

In [24]:
last_slice = np_array[2::3]
last_slice

array([[6, 7, 8]])

In [23]:
# slicing with (...)

In [15]:
first_slice = np_array[0,...]
first_slice

array([0, 1, 2])

In [18]:
last_slice = np_array[2,...]
last_slice

array([6, 7, 8])

Column wise slicing

In [19]:
first_column = np_array[...,0]
first_column

array([0, 3, 6])

In [20]:
second_column = np_array[...,1]
second_column

array([1, 4, 7])

In [21]:
third_column = np_array[...,2]
third_column

array([2, 5, 8])