<a href="https://colab.research.google.com/github/ShakilAhmedSumon/numpy_exersises/blob/main/numpy_exersise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np_array = np.array([[0,1,2], [3,4,5], [6,7,8]])

In [3]:
np_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Numpy Slicing 

In [4]:
middle_slice = np_array[1::3]

In [5]:
middle_slice

array([[3, 4, 5]])

In [14]:
first_slice = np_array[0::1]
first_slice

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1, 2],
       [6, 7, 8]])